[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "common_tools"
version = "0.1.0"
description = "Common utilities and tools for TLP Python"
authors = [{name = "Rudra Menon", email = "rmenon@enginius.ai"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*"]

